spring.application.name=tutorias


# Configuracion MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tutoriasbd}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Clave simple para operaciones de administrador
app.admin.key=${ADMIN_KEY:secret-admin}

# Configuración de correo electrónico para notificaciones
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:noreply.tutoruja@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email del profesor que recibirá las notificaciones
profesor.email=${PROFESOR_EMAIL:alabella@ujaen.es}

# URL base de la aplicación.
app.url=${APP_URL:http://localhost:8080}